window:
  title: "Pick Up Trash"
  width: 1280
  height: 720
player:
  speed: 10
  width: 70
  height: 90
trash:
  fall_speed: 3
  spawn_rate_ms: 2000 # Tần suất rác rơi (mili giây)
  width: 40
  height: 40
game:
  fps: 60